services:
  kutt-db:
    image: postgres:16
    restart: always
    volumes:
      - db_data_pg:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=kutt
      - POSTGRES_PASSWORD=YOUR_DB_PASSWORD
      - POSTGRES_USER=YOUD_DB_USER
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  kutt-redis:
    image: redis:6.0-alpine
    restart: always
    ports:
      - 6379:6379

volumes:
  db_data_pg:
  custom: